### ISSUE TITLE
Hopper Create

### ISSUE THREAD

**Issue by Milkpaw** [theseedmc/issues#1]
Cannot create Hopper in Skyblock.
I have all the needed materials (Chest+Iron Ingots), it shows up in the recipe book as able to be made(Silver border) but no item comes up to create it successfully. 

https://gyazo.com/944b2206518305697f5c3dd9f14c3e28

**Comment by gp-Airee** [comment]
AntiCraft is configured to not permit the crafting of hoppers and beacons. Seems to be functioning as intended.

**Comment by CircusCow** [comment]
Yes, this is intended.
