### ISSUE TITLE
Dungeons on Skyblock are non-functional

### ISSUE THREAD

**Issue by xenxero1** [theseedmc/issues#10]
**Describe the bug**
The dungeon system does not function properly, with mobs frequently not spawning and preventing further wave progress. Additionally some players have reported being able to break parts of the dungeon map, but due to a lack of teleport permissions, I was unable to confirm the location or action.

**To Reproduce**
1. Join a dungeon session. I believe it's `/ma join` without aliasing
2. Pick a class and wait for the dungeon to launch
3. Wait around and kill mobs if they spawn. Wave progress and spawning suddenly stops very early on.

**Expected behavior**
Waves should continue and not be interrupted.

**Comment by gp-Airee** [comment]
Dungeons are borked pretty hard. CircusCow is now looking for a solution.
