### ISSUE TITLE
KeepInventory

### ISSUE THREAD

**Issue by SirCrazynut** [theseedmc/issues#102]
**Is your feature request related to a problem? Please describe.**
I got kicked from the server while I was mining out a cavern and when I returned it said I had died, when I /back to my stuff it had all despawned, I lost all my max vanilla enchanted diamond tools plus a few other things, really frustrating

**Describe the solution you'd like**
Employ /keepinventory, maybe make it toggleable

**Describe alternatives you've considered**
Make it so that /keepinventory exists on any claim you are trusted on (again could be toggleable), but you can still lose items else where to keep the original Minecraft feel

**Additional context**
I know there was a poll a while ago, but it doesn't seem like there was any action or response

**Comment by gp-Airee** [comment]
no
