### ISSUE TITLE
Archduke weekly key gave me a votekey

### ISSUE THREAD

**Issue by Egzile** [theseedmc/issues#103]
when I collected my weekly archduke key today, it gave me a votekey

use archduke or whatever weekly key button and see which key it gives

I expected to get a useful key, not a votekey, which only gave me 1000 xp which is a whole other problem.
![image](https://user-images.githubusercontent.com/51899104/64998986-09f39680-d89b-11e9-8227-9135042cb778.png)
(mushroom)

**Comment by s33rgaz3** [comment]
The new /perk weekly key gives a random vote key/loot key/perk key now instead of a loot one every time.
