### ISSUE TITLE
Mob Heads dont drop

### ISSUE THREAD

**Issue by yudheer** [theseedmc/issues#11]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Mob heads do not seem to be dropping anymore.

**To Reproduce**
1.) Get a charged creeper, I personally tamed a creeper waited for a thunderstorm and then used a channeling trident to make it charged.
2.) Get a mob that drops a head when blown up by a charged creeper, I tamed a skeleton archer dude.
3.) release the mob that you want the head of next to the charged creeper and let the creeper
blow him up.
4.) If i am not mistaken the vanilla mechanic is that a mob that has a droppable head will drop its head 100% of the time if killed by a charged creeper, however no head drop occurs. I tried 3 times.

**Expected behavior**
Pretty much explained above but essentially a mob with a droppable head should always drop its head if killed by a charged creeper. This does not occur

**Comment by gp-Airee** [comment]
WildStacker is causing this. We're trying to get rid of it.

**Comment by gp-Airee** [comment]
Resolved with theseedmc/seed-casual-plugins@6d64c7215100d854606876a27abafe8362c80ba5
