### ISSUE TITLE
McMMO experience not granted when in a minecart

### ISSUE THREAD

**Issue by Zytan27** [theseedmc/issues#111]
**Describe the bug**
Please provide additional information too, depending on what you have issues with:

When breaking crops while riding in a minecart McMMO Herbalism experience isn't granted. Experience should be received whenever you manually break a stalk of sugarcane, and works correctly when running through a farm. I set up a minecart track to manually break all the stalks easier, but inside the minecart experience isn't registered. Jobs experience works correctly, but McMMO does not.

**To Reproduce**
1. Step up a minecart track next to sugarcane or other crops
2. Ride the minecart while breaking the crops
3. Notice no experience gain

**Expected behavior**
https://streamable.com/bw5hi
vs
https://streamable.com/aa74m

**Comment by gp-Airee** [comment]
This is a mechanism to prevent auto-farming. See relevant code here: https://github.com/mcMMO-Dev/mcMMO/blob/dda894dd9a5cfbf1ce6ad013a962623c92fc6492/src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java#L134

There is an explicit check for player in vehicle, ends function for giving EXP short.
