### ISSUE TITLE
redstone does not work in claims

### ISSUE THREAD

**Issue by MrKitCat1210** [theseedmc/issues#112]
**Describe the bug**
claiming land makes redstone work in a very odd way when i have a piston door in claimed land the piston door makes the pistons break and not move it only worked normally when i unclaimed the land so my base is unclaimed, please fix this if it is in your ability to do so.

**to Reproduce**
1. Go to your claimed land
2. Do make a piston door i would say one that opens up the floor (that works best in this situation when trying to reproduce it)
3. Click on a button that activates the door
4. See bug occouring
![2019-11-16_11 17 41](https://user-images.githubusercontent.com/57841114/68996691-f9dc4100-0862-11ea-8c89-e49b5c92288d.png)
![2019-11-16_11 18 12](https://user-images.githubusercontent.com/57841114/68996693-fea0f500-0862-11ea-8a5a-e26c9b3a9b55.png)

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by yungwilder** [comment]
is every component of the contraption within the claim, including the button (not just the block the button may be placed on)
