### ISSUE TITLE
Game closes while enchanting an item

### ISSUE THREAD

**Issue by Telendar** [theseedmc/issues#116]
Happened four times in a row and happened to my friend as well: When using an anvil to enchant, the game closes (not a crash since it displays a "Saving world" message).

This happened with a diamond pickaxe with no enchantments. The pickaxe drops to the ground.

I am using 1.15 client. It stopped happening when I changed back to 1.14.4

**Comment by gp-Airee** [comment]
1.15 is protocol hacked. We will have to wait for a patch from ViaVer.
