### ISSUE TITLE
Mob Killing jobs seem to be not paying out on mushroom

### ISSUE THREAD

**Issue by Egzile** [theseedmc/issues#12]
Hunter job not paying any money (or any jobs for killing hostile mobs)
seems to only be an issue on mushroom, jobs worked fine on pumpkin
tested with 2 other people, they didn't get payed either.

to reproduce, go to mushroom, choose hunter job, then go to /warp lab 6 and test.

![2019-06-19_23 34 35](https://user-images.githubusercontent.com/51899104/59826583-6faba300-92eb-11e9-96f9-0ad1fbf0995c.png)

**Comment by gp-Airee** [comment]
This is not a bug. We're working on preventing jobs from paying out from mob spawner mobs.
