### ISSUE TITLE
Written Books have their metadata loss or changed on logout

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#120]
**Describe the bug**
Upon server switch or logging out, there is a chance that copies of written books will have their nbt or metadata changed.

**To Reproduce**
1. Make a written/signed book
2. Make multiple copies of that book
3. Leave a some of them in a chest and take a few with you to test
4. Logout, switch servers, the exact replication step is unknown to me
5. Check that the books still stack with the books in the chest

I have multiple stacks of bugged books if you want to look.

**Expected behavior**
I expect books that originally belonged to the same stack to retain the data to continue to do so.

**Comment by gp-Airee** [comment]
This is an issue with serializing the inventory contents on log off for storage in database. Devteam for SeedSync has been informed.

**Comment by gp-Airee** [comment]
Should be fixed, I fucking hope
