### ISSUE TITLE
Ability to create shops on other players claimed land

### ISSUE THREAD

**Issue by X11-OmegalingYT** [theseedmc/issues#122]
There is a bug happening where other players can create shops on other players land claims, locking them out of their storage systems and allowing players to steal items from shops

This can be done the same way you make a shop, but it works on other players land claims.

When created, you lock players, including the claim owner, out of the chest, you can buy items for a cheap price and it will take items out of the chest.

**Comment by gp-Airee** [comment]
Should be fixed.

**Comment by X11-OmegalingYT** [comment]
Ive just checked, its not fixed
