### ISSUE TITLE
Archduke Double Jump Pseudo Fly Hacks

### ISSUE THREAD

**Issue by APills** [theseedmc/issues#123]
**Describe the bug**
Archduke Double Jump allows pseudo fly hacks, this is most noticeable during lag spikes in which you can fly for the entire lag spike duration but doesn't require much to pull off. I am able to do this consistently and access areas that would require multiple jumps, or more travel time.
![gif of this happening](https://user-images.githubusercontent.com/47908299/71551024-211e4600-29ab-11ea-9600-86703df17691.gif)

**To Reproduce**
1. Double Jump while moving

**Expected behavior**
The Double Jump doesn't occur or is delayed

**Comment by gp-Airee** [comment]
This is a problem with lag. We'll need to deal with lag to fix this.
