### ISSUE TITLE
my home tp me to spawn

### ISSUE THREAD

**Issue by quinzecaractere** [theseedmc/issues#125]
I've made a sethome in an end city(far away from spawn) and I could use it like any other home that I've made, until for some reason it decided that the warp is too far away.every time I try to use it, it tells me that I've passed the world border and teleport me at spawn if I'm in the overworld, and at x:0 y:50 z:0 if I do it while being in the nether or end (doing it in the nether tp me in the nether and doing if in the end tp me in the end).

**To Reproduce**
you can't really reproduce it since you don't have access to my homes, but it'd be:
1. Type "/home fin"
2. See bug occouring

**Expected behavior**
I expected to tp me where I did /sethome.

![2019-12-30_23 04 27](https://user-images.githubusercontent.com/59375674/71602590-66807600-2b59-11ea-9ca0-35f4efdeb0ef.png)
![2019-12-30_23 04 30](https://user-images.githubusercontent.com/59375674/71602621-89128f00-2b59-11ea-834b-4b8ecfc271e0.png)
![2019-12-30_23 05 09](https://user-images.githubusercontent.com/59375674/71602629-8ca61600-2b59-11ea-84e5-9f5fb581f320.png)
![2019-12-30_23 05 14](https://user-images.githubusercontent.com/59375674/71602631-8fa10680-2b59-11ea-8316-e7d872755934.png)
![2019-12-30_23 05 32](https://user-images.githubusercontent.com/59375674/71602634-929bf700-2b59-11ea-883b-9b9f786062ea.png)
![2019-12-30_23 05 38](https://user-images.githubusercontent.com/59375674/71602639-94fe5100-2b59-11ea-8081-c3d037618912.png)
![2019-12-30_23 07 55](https://user-images.githubusercontent.com/59375674/71602643-9891d800-2b59-11ea-920c-dd019129d2ca.png)
![2019-12-30_23 08 04](https://user-images.githubusercontent.com/59375674/71602645-9a5b9b80-2b59-11ea-8a7b-d3a0b3f56db1.png)

**Comment by gp-Airee** [comment]
End worldborder was shrunk by @CircusCow.
