### ISSUE TITLE
Not getting playtime rank money

### ISSUE THREAD

**Issue by Iggley** [theseedmc/issues#128]
**Describe the bug**

Player emcv12 is a settler and has a sister blackie26
Blackie26 has got playtime rank money in nomad and settler rank, but emcv12 has not got it, apparently no text or anything showed up when they ranked up

**To Reproduce**

Not sure how to reproduce but it could be to do with them being on the same ip 

**Expected behavior**

Nothing happens when they pass the playtime required to rank up

**Comment by gp-Airee** [comment]
Fixed.
