### ISSUE TITLE
Voting didnt work 

### ISSUE THREAD

**Issue by Egzile** [theseedmc/issues#13]
tried voting today, and it didn't register

/vote next still says "go vote"

![image](https://user-images.githubusercontent.com/51899104/59828967-0e86ce00-92f1-11e9-8192-29e6487cc19e.png)

**Comment by Egzile** [comment]
this is my last day b4 weekly, so I hope it gets figured out fast XD

**Comment by Egzile** [comment]
also, kolbae had the same issue

**Comment by gp-Airee** [comment]
Known issue regarding new proxy setup. Looking for solution.

**Comment by gp-Airee** [comment]
Progress started on theseedmc/multiproxy-vote-forward to resolve this issue.

**Comment by Hedwig7s** [comment]
Its true its still not working today

**Comment by gp-Airee** [comment]
theseedmc/multiproxy-vote-forward resolves this.
