### ISSUE TITLE
Nether Portals and World Border

### ISSUE THREAD

**Issue by Iggley** [theseedmc/issues#130]
**Describe the bug**

With nether portals which are beyond 7k in the overworld, if you go into the nether through them and straight back through that portal it takes you to 7k on that coordinate instead of the original portal. For example: 
-131 64 9909 goes to -132 53 6697
-13855 71 20345 goes to -6996 59 6997

**To Reproduce**
1. Go to any overworld portal which is outside 7k in at least one coordinate
2. Go through the portal into the nether and come back
4. See bug occouring

**Expected behavior**
Will take you to 7k instead of the original coordinates.

**Comment by DSchaedler** [comment]
Had a similar problem with a portal around -1000 7000. Coming back through the portal sent me to 0 0 however.
