### ISSUE TITLE
Store join noftification issue

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#133]
**Describe the bug**
The economy message when joining informing you of sales is repeating the same sale.
![image](https://user-images.githubusercontent.com/51970925/71772460-2fbfac80-2f19-11ea-9fb6-5ca1fecddc17.png)

**To Reproduce**
1, Have a sale made offline
2. Log in
3. Log out/in again
4. See message
5. Repeat 2-4 and see same message

**Expected behavior**
I expect the shop message to show a new relevant message on join.

**Comment by Declyn4405** [comment]
Fixed
