### ISSUE TITLE
/perk perm potion slots not working

### ISSUE THREAD

**Issue by Leviathanuwu** [theseedmc/issues#134]
I bought the 5x perk key pack and had used them on the perk chests, i won two perm potion slots, yet when i tried getting the perm potion effects, it said i had to be a donor, or get a rank, kinda weird tho that i bought the keys, got the reward, yet cant use em.

1. win a perm potion slot, make sure you dont have a rank
2. Do /perks and click on the permanent potions item
3. Says you have to be a donor
4. No potion affect

I just want what i paid for lol, i'll drop a screenshot below for proof of payment
[[  removed by airee - personal information  ]]
.

**Comment by gp-Airee** [comment]
Currently reworking the way the potion slots work. As of now, what's your username? I can just give you a donor rank so you can access it.

**Comment by Leviathanuwu** [comment]
Leviathan_uwu
Do i have to be online to get it? I just got off like 5 mins ago.

**Comment by gp-Airee** [comment]
Should be fixed.
