### ISSUE TITLE
Too many items when pets kill mobs from spawners

### ISSUE THREAD

**Issue by morimoth** [theseedmc/issues#136]
A possible bug that's been reported by elaineandsparky:

It appears that when a pet attacks a mob from a spawner, way too many items are dropping then there should be.

e.g. when elaine's pet cow attacks a sheep from a spawner, stacks upon stacks of meat and wool drop.

[Here is in action](https://drive.google.com/file/d/1KIWEKI8MAvbDwhYTIKENUaMjK90sgf7v/view?usp=sharing)

_(i doubt the video link will work since it doesn't for me, but hey maybe it will)_

**Comment by gp-Airee** [comment]
Resolved
