### ISSUE TITLE
Instant Death While Flying In /warp End

### ISSUE THREAD

**Issue by LoganLeigh4** [theseedmc/issues#137]
I was flying in /warp end in the North-East direction at about Y 130-133 and was instantly killed. The chat said I "fell into the void".

1: Go to /warp end and equip an elytra, and head north-east
2: Begin flying and go out about 500 ish blocks, and upwards 130 blocks
3: You will instantly die or take massive amounts of damage that the void couldn't cause normally.

Expected Behavior was that I would be able to fly in the end like normal to enjoy the end reset. I lost my nightmare helmet, leggings and boots and legends elytra and 4 stacks of fireworks.

Edit: My ign is Mxthical and my discord is Mythical

**Comment by yungwilder** [comment]
@gp-Airee just want you to get a notif; seems high priority imo

**Comment by DomNukem** [comment]
I also had a similar experience while flying at around Y - 180. I was no where near the void or near the world border. I was even monitoring my coordinates (as I don’t like to die with approx 500k+ in loot and gear including my legends elytra, legends sword, and a bunch of shulker shells from raiding.) 

This occurred on mushroom realm for me.

**Comment by gp-Airee** [comment]
Can't reproduce
