### ISSUE TITLE
Economy notification when coming back online does not work properly

### ISSUE THREAD

**Issue by koreghan** [theseedmc/issues#138]
For a couple weeks now I have noticed that when logging in the chat doesn't say who bought out my items from my shop like the economy normally would. Instead it will repeat a message like "so and so bought 5 chorus fruit" but that happened over 4 days ago, plus it happened when i was online and it just popped up in chat, it wasn't a purchase made offline that the system should tell me about when i join back online.

1. Log onto the Seed minecraft server
2. I join Mushroom
3. I open the chat and i go to where the economy/system notification would pop up in chat
4. See bug occurring

I would expect to see a couple of lines worth of items bought out by other players, usually things like leather, blocks, etc. Also I expect to see that some of my shops are now empty and that I need to restock.

**Comment by gp-Airee** [comment]
on hold

**Comment by Declyn4405** [comment]
Fixed.
