### ISSUE TITLE
/playtime ranks not working (mushroom)

### ISSUE THREAD

**Issue by Egzile** [theseedmc/issues#14]
so, multiple people today have been questioning when they will rank up. they are always newcomers with well over an hour playtime. and they  didn't become nomad.

![2019-06-20_00 41 41](https://user-images.githubusercontent.com/51899104/59830300-3592cf00-92f4-11e9-9e3d-fd68550a1c86.png)

**Comment by Egzile** [comment]
someone became nomad abruptly
yet, it didn't rly work for anyone else

**Comment by nkomarn** [comment]
Working on rewriting the detection system to have a fallback in case the method to give rewards doesn't fire on time.

**Comment by gp-Airee** [comment]
Resolved by theseedmc/seedplaytime@e5968a7fb4fa935db4a447adef627d4ec566ddf6
