### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by MrSmite19** [theseedmc/issues#140]
I have been voting daily for the server and constantly getting bugs where my votes aren't going through from the website to the server. It will say that the vote was successful yet not count for me well in the server. I am online when voting as well as using the same device so that there wont be able chance of a problem occurring that yet one still manages to find itself there.

**Comment by yungwilder** [comment]
Make sure you are using your full, correct IGN. Countless people have made a small mistake in their name for days and not noticed.

**Comment by gp-Airee** [comment]
Closed by SeedVoteRewards + SeedVoteShop

**Comment by gp-Airee** [comment]
Closed by SeedVoteRewards + SeedVoteShop
