### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by Alex80IR** [theseedmc/issues#143]
Mobs are acting very passive against blocks or stuffs around them.
Like on melon I myself noticed that my auto cooker(/Warp XPE)
 doesn't work properly while it was working OK for a long time but suddenly something about server changed and cows and sheep started suffocating in blocks instead of falling into death point by piston's push.

![2020-01-20_12 05 48](https://user-images.githubusercontent.com/60090979/72711013-7f3ee300-3b7d-11ea-9f1b-428f00553641.png)

The second example of this issue was about squids auto farm which you can check on melon realm (/Warp Ink) now squids are passive against the cobwebs while they weren't before. 

squids before issue (taking damage by cobwebs)
![2020-01-20_12 05 04](https://user-images.githubusercontent.com/60090979/72711072-9a115780-3b7d-11ea-89f3-7b51f6f2a153.png)

squids now (taking no damage from cobwebs)
![2020-01-20_12 04 43](https://user-images.githubusercontent.com/60090979/72711093-a1d0fc00-3b7d-11ea-986e-84c7e97e2e03.png)

One more thing I want to mention is about Mobs render which I got screenshots for that to make it clear what I mean about mob render : 

When you step in a chunk contains villagers it loads the chunk but doesn't show the villagers I even waited like about 5 minutes to test if it is about my internet but for example here in this screenshot it didn't show the cleric behind his station.
![2020-01-20_12 15 20](https://user-images.githubusercontent.com/60090979/72711715-cf6a7500-3b7e-11ea-84b4-fc6c47268926.png)

This time I did a teleport(random) then did /back and it showed the cleric which wasn't being showed in previous screenshot : 
![2020-01-20_12 15 43](https://user-images.githubusercontent.com/60090979/72711922-4bfd5380-3b7f-11ea-966c-df33a32f1eb1.png)

**Comment by epicc97** [comment]
I have noticed this happen also, the pistons don't push Mobs even with a Normal piston it is supposed to push them off the block but for some reason they stay on or go to fall off but then like teleport back and get stuck where the piston is out

**Comment by gp-Airee** [comment]
Can't reproduce.
