### ISSUE TITLE
Black Text Code on Items

### ISSUE THREAD

**Issue by Shwxzzy** [theseedmc/issues#146]
**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Color coded items with the color Black do not stay black upon relog.

**To Reproduce**
1. Rename item with the Black Code (any name)
2. Log out
3. log back in
4. Black color is gone

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Uh, I expect the color to stay there. Like the other codes do.

**Comment by gp-Airee** [comment]
reproduced
