### ISSUE TITLE
"Flying" Bug with Jump Boost II and Blocks in claims where you have no permission

### ISSUE THREAD

**Issue by AkA-Acid** [theseedmc/issues#151]
The bug is that when you continue to place blocks under you while you are attached to a wall and you have jump boost II you like fly and you can continue to jump while in the air but the server thinks that you are on top of a block so you can jump again and like that you fly.
Please provide additional information too, depending on what you have issues with:

How To Reproduce The Bug
1. Go to a person's claim where you aren't trusted; 
2. Go to a high wall;
3. Continue to place blocks under you while you keep the space bar pressed;
You will be able to fly by jumping on the blocks that you placed, you have a minimal time to get the jump correctly, it will work after a few tries.

**Comment by gp-Airee** [comment]
Can't resolve.
