### ISSUE TITLE
Duke Double-Jump Bug

### ISSUE THREAD

**Issue by MyEyesBurn-Loki** [theseedmc/issues#152]
**Describe the bug**
Dukes gain fly from enabling double jump.

**To Reproduce**
1. Be Duke Rank
2. Enable Double Jump (Which they shouldn't have access to?)
3. Try to double jump
4. Fly

**Expected behavior**
When they double jump, they will be put into fly mode.

**Comment by gp-Airee** [comment]
Resolved.
