### ISSUE TITLE
MCMMO Double Drop Chance not Working on Ores

### ISSUE THREAD

**Issue by Snickerswhirr** [theseedmc/issues#155]
MCMMO Double Drop chance from mining skill isn't working on silk touched items even though it was previously working.

Please provide additional information too, depending on what you have issues with:
Should be dropping double drop at some point. Even when chance is 38% recieved ZERO double drops out of a 40 ore vein.

**To Reproduce**
1. Go to natural spawn ore vein
2. Break with silk touch
3.  Will not receive double drop.

**Expected behavior**
Some double drops expected. Player pizzadragon5901 on pumpkin has 65% double drop chest and hasn't been receiving any double drops after multiple veins and mining sessions today (3/4)

**Comment by gp-Airee** [comment]
Working as intended
