### ISSUE TITLE
Channel not working

### ISSUE THREAD

**Issue by Snickerswhirr** [theseedmc/issues#156]
DESCRIPTION OF BUG:
Channel is not working. When you select trade channel and talk in it, it appears that no messages send. Even leaving and reentering does nothing.
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
1. Go to /channel
2. Select talk in trade as well as view trade channel
3. type in chat like normal
4. message doesn't send, and testing with someone across another realm they also didn't see any message go through

**Expected behavior**
A message to send in trade channel that can be viewed through all realms. 
[Small video of the chat not going through](https://imgur.com/B8dQrMD)

**Comment by gp-Airee** [comment]
can't reproduce/fixed
