### ISSUE TITLE
Others still able to pick up item even after disabling the effect of /unlockdrops (aka die after enabling)

### ISSUE THREAD

**Issue by GodFlameTIC** [theseedmc/issues#165]
**Describe the bug**

- Dying after enabling /unlockdrops does not undo its effect.

Please provide additional information too, depending on what you have issues with:

- I've died a couple of times after the /unlockdrops is enabled. The first time I died after using /unlockdrops is tested by a friend on Pumpkin, and he cannot pick it up for the 2nd time - that sounds fine. I've also tested this on Melon (enabling /unlockdrops and get killed, then get killed again and items cannot be picked up in 2nd time) , which also seems fine. However, when I died in the dungeon in Pumpkin (did not enable /unlockdrops), a player managed to pick up the items (and return them)

**To Reproduce**
1. Go to any of the realms
2. Do /unlockdrops
3. Get killed - undo effect
4. Switch to a different realm
5. (repeat 2 and 3)
6. Leave the server.
7. Return to the first realm (do not enable /unlockdrops)
8. Die in the dungeon, with someone there to pick up items
9. See bug occurring

**Expected behavior**
Dying after enabling /unlockdrops should reverse its effect.

**Comment by yungwilder** [comment]
This is an issue with dungeons, not /unlockdrops, as the instances where you tested that command outside of the dungeon it worked fine.
