### ISSUE TITLE
Night Vision Goggles don't work properly

### ISSUE THREAD

**Issue by AkA-Acid** [theseedmc/issues#169]
Hello, when I am wearing tmy night vision goggles, I see the lights flick from night vision effect to no night vision effect, it's continoius and if I restart the game it's still there. I tried to start the game without optifine, as riskyosto told me to do, and the issue is still there.

**Comment by RedDropsofRain** [comment]
Hi Acid,

I reported this issue yesterday, and I believe it's because the Night Vision Goggles continuously applies nine seconds of night vision. The screen will flash if there are ten seconds or less of the effect.

**Comment by Declyn4405** [comment]
Fixed, thanks.
