### ISSUE TITLE
When using a parrot or pet with slow falling , you can fall into the void.

### ISSUE THREAD

**Issue by Faibelix** [theseedmc/issues#172]
**Describe the bug**
When you use a parrot or pet with slow falling to fly . You won't land when going down but instead you keep falling . Eventually you will even go through bedrock and fall into the void. This is not visual because when you get of your pet you are able to dick yourself out of the ground and people can see you fall down deep into the ground .

**To Reproduce**
1. Go to : Somewhere in the world , I personally play on pumpking.
2. Do : Get a parrot pet and use the ride skill tree.
3. Click on : the parrot with a lead , fly up for some time and try to land without getting of off your pet. You won't hit the floor but go right through it.
4. See bug occouring

**Expected behavior**
When landing you should end up standing on top of the ground. Not go right through it.

**Comment by gkp1** [comment]
This happened to me everywhere in the end so I left because I'd end up dead. 

I use a chicken. I had no idea why it was happening.

**Comment by gp-Airee** [comment]
Fixed.
