### ISSUE TITLE
Bees consistently fly through solid blocks

### ISSUE THREAD

**Issue by felinefuschia** [theseedmc/issues#174]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES. IF YOU DON'T USE THE TEMPLATE, THIS ISSUE WILL BE CLOSED.**

**Describe the bug**
I know bees are a newer feature to the game, but I'm continuing to have a problem keeping them contained.  It seems that they are able to fly through (not spawn around) solid blocks at block junctures, like a corner.

**To Reproduce**
1. Go to 'bee area, place where bees are being kept, breed bees, etc.'
2. Do 'set up area where bees are kept'
3. Click on '....'
4. See bug occurring 'bees flying through solid bricks in the corners'

**Expected behavior**
I've tried changing blocks, it seems to be the most prominent of an issue with glass blocks but they've also found their way through honey blocks.

**Comment by gp-Airee** [comment]
Fixed.
