### ISSUE TITLE
Bug with Scaffolding

### ISSUE THREAD

**Issue by 0fen** [theseedmc/issues#176]
The Bug I found happens when you are standing on a scaffolding block that is about to fall down. When rightclicking quickly on an existing scaffolding block some scaffolding blocks will appear to fly in the air. Then you can stand on them until you get kicked for flying.
To reproduce:
1. Stack yourself up with scaffolding
2. walk in one direction with the scaffolding until they fall down
3. click rclick a couple of times quickly 
4. Jump on the flying scaffolding block
5. get kicked for flying

I´m not sure if this is an issue but I was told to report it anyways.

**Comment by gp-Airee** [comment]
Flight kicking has been disabled. Shouldn't have been on.
