### ISSUE TITLE
Glitched Villager

### ISSUE THREAD

**Issue by TheGreatPotat0** [theseedmc/issues#177]
I found an unclaimed village with wild villagers in it a 5 min boat ride from my claim, i placed the villager in my boat and took him back to my claim. However he won't settle right on my claim, after setting up his playpen I broke the boat and he just, floated, a half block in mid air and is unmovable by bumping or hostile mobs. He won't run any where even to bed when it is night. he just.... floats....

**Comment by gp-Airee** [comment]
Can't reproduce.
