### ISSUE TITLE
TNT Duper Breaking

### ISSUE THREAD

**Issue by Snickerswhirr** [theseedmc/issues#179]
**Describe the bug**
When placing the piston to use the tnt duper it turns the minecart and the piston disappears, which causes the tnt not to duplicate
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
1. create a tnt duper
2. activate the piston
3. minecart will turn and piston will disappear

**Expected behavior**
tnt to dupe properly. According to players it was working previously and has only recently broken, maybe a recent optimization update broke them? Unclear ;-; 

[short video of it not working](https://imgur.com/a/Ft4CI1I)

EDIT**** Upon further evaluation of the issue, it seems to be that when you place the activator rail and then activate the piston, when the piston moves it disappears. 

[Video of piston disappearing after the Rail was placed](https://imgur.com/a/bXFslQx)

**Comment by gp-Airee** [comment]
Most likely fixed with the removal of IllegalStack.
