### ISSUE TITLE
Nickname change not working

### ISSUE THREAD

**Issue by Sensunae** [theseedmc/issues#182]
**keep in mind that there are no steps to replicate this bug**

This bug makes it so you can't change your nickname period, even a mod can't change your nickname

If you do /nickname &cSensu&dnae then it will say in chat that it changed my name, but when i typed it wouldn't change my name, my name would stay default

**steps i took to try and resolve this before reporting this bug:**
----

Relogged

Closing mc launcher and relaunching

Reset pc

Waited for daily reboot

---
It seems to be a bug only i've encountered.

**Comment by gp-Airee** [comment]
Can't reproduce
