### ISSUE TITLE
MCMMO issue: Haste potions vanish from inventory after being removed from brew stand.

### ISSUE THREAD

**Issue by stygian1** [theseedmc/issues#183]
**To Reproduce**
1. Go to 'brewing stand'
2. Do 'brew haste potions' (unlocked at alchemy 250 via mcmmo)
3. Click on 'potion of haste' and move it into your inventory
4. See bug occuring: after about one second, the potion(s) are removed from your inventory.

Theory: They are being detected as cheat items by the cheat prevention plugin, possibly due to the last bugfix.

**Expected behavior**
The expected behavior is that the item crafted will remain in your inventory, as per any other potion brewed.

**Comment by gp-Airee** [comment]
Fixed with removal of IllegalStack
