### ISSUE TITLE
Night Vision Goggles have been broken for weeks...

### ISSUE THREAD

**Issue by lazerpirate** [theseedmc/issues#186]
**Describe the bug**
Please provide additional information too, depending on what you have issues with: Night vision goggles are stuck in a flickering mode, it has been this way for weeks. When wearing them it just strobes and gives you a headache. It started with the patch that brought in the easter keys, so my guess is it has to do with the buff timers that were changed to allow things like the "easter bunny" to exist. 

**To Reproduce**
Wear Night Vision Goggles
Blinking strobing...

**Expected behavior**

https://gyazo.com/e753836ab9fd302233c866817051d806

**Comment by gp-Airee** [comment]
Fixed
