### ISSUE TITLE
Broken Villagers

### ISSUE THREAD

**Issue by Frozenbloo** [theseedmc/issues#188]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES. IF YOU DON'T USE THE TEMPLATE, THIS ISSUE WILL BE CLOSED.**

**Describe the bug**
When you remove villagers from a boat, the villagers will freeze and float a half block in the air.

**To Reproduce**
1. Put a Villager In A Boat
2. Destroy The Boat
3. See bug occouring

This is an Image Of What Happens
![2020-04-27_13 36 05](https://user-images.githubusercontent.com/61006165/80372918-2ffb0380-888c-11ea-99b5-79a4c9f1f857.png)

**Expected behavior**
Villager would fall to the ground and it's AI would act normally

**Comment by gp-Airee** [comment]
Can't reproduced, probably fixed?
