### ISSUE TITLE
Horses can't be tamed

### ISSUE THREAD

**Issue by saiomori** [theseedmc/issues#189]
**Describe the bug**
Please provide additional information too, depending on what you have issues with:
When trying to tame a horse, the horse doesn't do anything nor is it tamed.

**To Reproduce**
1. Find a wild horse
2. try to ride it and wait
3. nothing happens

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

What is expected to happen is to have the horse moving. It should also throw you off of its back or show hearts, but it doesnt do any of this.

**Comment by gp-Airee** [comment]
Can't reproduce
