### ISSUE TITLE
Treasure fishing

### ISSUE THREAD

**Issue by tyrantium** [theseedmc/issues#19]
**Describe the bug**
Treasure fishing does not work
Please provide additional information too, depending on what you have issues with:
This literally does not work i have fished over 185 fish by this time and NOT ONCE have I gotten a treasure

**To Reproduce**
1. Go to Water
2. Use fishing rod
3. Repeat as many times as you want
4. See bug occouring

**Expected behavior**
It's supposed to fish some treasure sometimes but it doesn't I guess

**Comment by tyrantium** [comment]
Airee if you don't fix this im starting ww3

**Comment by gp-Airee** [comment]
@tyrantium is this an McMMO feature or vanilla feature? this may be controlled by mcmmo if it's vanilla.

**Comment by gp-Airee** [comment]
Working as intended.
