### ISSUE TITLE
Resource Kit - Only 2 NetherBrick Blocks

### ISSUE THREAD

**Issue by Frozenbloo** [theseedmc/issues#192]
**Describe the bug**
The Resources Kit Only Gives 2 Nether Brick Blocks

**To Reproduce**
1. Go to /kits
2. Claim the Resource Kit
4. See bug occouring

**Expected behavior**
You Should get 64 Nether Brick Blocks.

**Comment by gp-Airee** [comment]
Pending kits recode, closing.
