### ISSUE TITLE
Deleted home switching realms

### ISSUE THREAD

**Issue by lukeybabe01** [theseedmc/issues#193]
I joined the melon realm today and found that I spawned in the spawn area instead of where I last was, after trying /home it again took my to spawn and not my actual home. In addition it also showed the “please welcome to the melon realm” every tome I rejoined the realm
From either the lobby or pumpkin realm (I didn’t test from mushroom) join the melon realm and this bug occurred and reset me to spawn each time 

Every time I left the realm and came back I would start at /spawn with the welcome to the realm message as if I was joining for the first time, and my home (but not warps) were deleted.

**Comment by gp-Airee** [comment]
Fixed.
