### ISSUE TITLE
/rtp issues

### ISSUE THREAD

**Issue by Mario90909** [theseedmc/issues#194]
Whenever I do /rtp for the last 8 times in a row I've ended up in the same exact desert with an ocean and acacia biome always directly next to it

**To Reproduce**
1. Go to chat
2. Do /rtp
3. Click on enter key
4. See bug occurring

**Expected behavior**
I've always in the past when using this have never gone to the same place once. Only today 5/11/20 have I started to see this issue

**Comment by gp-Airee** [comment]
Fixed
