### ISSUE TITLE
The Warp limit seems to be off or broked since the warp update

### ISSUE THREAD

**Issue by Egzile** [theseedmc/issues#2]
The Bug is that I should be allowed 15 warps as archduke and now I only have 9
tried deleting and remaking and it made my limit smaller

literally cant make more than 9 warps
and it worked fine b4 the warp update

![2019-06-16_22 49 14](https://user-images.githubusercontent.com/51899104/59581307-4f7ca980-9089-11e9-8c72-222745e9264e.png)

**Comment by gp-Airee** [comment]
@CircusCow Contact Mykyta- SimpleWarp seems to not be working with the warp.max permission node. LuckPerms has it configured properly. Perhaps they are getting the first "warp.max" permission node SimpleWarp evaluates to be true, rather than the highest?

**Comment by CircusCow** [comment]
I am in contact with the dev regarding this issue. Please be patient as we continue to look into it. Thanks.

**Comment by gp-Airee** [comment]
@theseedmc/developers

**Comment by nkomarn** [comment]
Working on it- @gp-Airee you're most likely right about the issue.

**Comment by nkomarn** [comment]
Resolved, hotfix implemented. It now selects the greater of the two permission nodes for the limit.
![image](https://user-images.githubusercontent.com/22900187/59635903-20a51880-9107-11e9-9d3f-aebae9b703a5.png)

**Comment by gp-Airee** [comment]
Fix has been pushed to production. Closing by theseedmc/seed-casual-plugins@03642b7a21f428e40565a8f4969ab41d81f8ad31.
