### ISSUE TITLE
Log of items sold while offline

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#20]
**Is your feature request related to a problem? Please describe.**
It is tiring to have to check every chest in my shop everytime I sell something while not logged in (I don't even have that many shop chests)

**Describe the solution you'd like**
A simple log of what was sold, who purchased it, and the same total ammount that is currently shown on login. 

**Describe alternatives you've considered**
A log link in chat that when clicked gives you a book with the log in it. (chat log is probably the easier route)

**Comment by yungwilder** [comment]
Also if this is already in game as a command I think this still stands as an improvement, but would still like to know if it is a command already.

**Comment by CircusCow** [comment]
I think this would be a great addition. I will talk to my dev about this.

**Comment by nkomarn** [comment]
> I think this would be a great addition. I will talk to my dev about this.

ChestShop API would make this possible (everything is event-driven)!

**Comment by gp-Airee** [comment]
In progress theseedmc/SeedCSExtras
