### ISSUE TITLE
mapart bug

### ISSUE THREAD

**Issue by dirt10** [theseedmc/issues#201]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES. IF YOU DON'T USE THE TEMPLATE, THIS ISSUE WILL BE CLOSED.**

**Describe the bug**
Taking mapart to other realms sometimes gives you a free copy of mapart that you arent supposed to have

**To Reproduce**
keep on trying to take mapart to other realms then it will show u a diffrent one

**Expected behavior**
it should have a diffrent mapart

**Comment by yungwilder** [comment]
Map art cannot transfer realms. Map data is tied to the world you are in, so this is expected behavior.
