### ISSUE TITLE
Mounting pet erases /back

### ISSUE THREAD

**Issue by gkp1** [theseedmc/issues#202]
**Describe the bug**
Mounting then dismounting from your MyPet sets your last location to where you mounted.

**To Reproduce**
1. Mount pet
2. Dismount
3. Send /back
4. See bug ocurring

**Expected behavior**
Dismounting pet shouldn't erase where you last teleported to

**Comment by gp-Airee** [comment]
Unfortunately, /back is extremely simple and we do not have the option of
manually defining every kind of teleportation to record with /back manually
across all of our systems. There will not be a resolution to this issue.
