### ISSUE TITLE
/collectbox interface doesn't work properly

### ISSUE THREAD

**Issue by 21C-O** [theseedmc/issues#206]
The collect box interface isn't working properly. You can still use /collectbox and then use your inventory normally, but you can't actually place items in the slots.

This occurs inside the /collectbox interface:
1. Run "/collect" or "/collectbox" in the chat
2. You're in the interface, where the problem is

Before, /collectbox would open the interface, allow you to place items inside the separate slots, and would be destroyed after closing the interface. You wouldn't be able to remove items from the /collectbox slots.

*(present issue)*
![issue_thing](https://user-images.githubusercontent.com/66579820/83989745-66a94c80-a915-11ea-9de9-62a5bcc2feec.gif)

**Comment by gp-Airee** [comment]
Please update the issue using the format or it'll be closed. I have questions that would be answered by the bug report format.

**Comment by 21C-O** [comment]
I fixed some parts of the report, I did misread some of the instructions. Also, the issue with placing the items back in your inventory was because I was using the Forge client.

**Comment by gp-Airee** [comment]
Collect box isn't a disposal. As the same suggests it's a box designed to claim items from. Presently only the server auctions place items it it, and we haven't done one in a while.
