### ISSUE TITLE
High-drop mob grinder stacking mobs when they're supposed to be dying

### ISSUE THREAD

**Issue by deathbytalkshow** [theseedmc/issues#22]
Witch grinder with a drop height of 37 blocks is not killing the witches instantly. Instead most are stacking together. Drops are significantly lower now that the majority of the mobs are stacking. It's not a XP grinder, it's a grinder for the mob drops so they're supposed to die instantly. 37 blocks height is more than enough to kill witches instantly.

**To Reproduce**
1. Go to /warp midgp that's the afk spot to turn on the spawners. wait a few minutes for witches to drop, maybe 5 minutes. Go outside and down the ladders to the bottom where the witches meet the ground where the hoppers are supposed to pick up gunpowder. You'll see a collection of witches like the screenshot provided.
![Screenshot from 2019-06-20 17-23-47](https://user-images.githubusercontent.com/9910773/59891487-2eb69b80-938a-11e9-8336-aafd3ef82b59.png)

**Expected behavior**
Them witches need to be dying. They're not.

**Comment by nkomarn** [comment]
Working on a fix.

**Comment by gp-Airee** [comment]
Resolved with theseedmc/seed-stacker

**Comment by deathbytalkshow** [comment]
You rendered it useless.
