### ISSUE TITLE
Stacked mobs (hostile) completely lose their AI

### ISSUE THREAD

**Issue by tyrantium** [theseedmc/issues#25]
**Describe the bug**
When hostile mobs are spawned by spawners (and or stacked) they completely lose their AI
Please provide additional information too, depending on what you have issues with:
They don't attack, don't move, they're just there, being a ragdoll

**To Reproduce**
1. Go to spawner
2. stand
3. See bug occouring

**Expected behavior**
mob does nothing, doesnt attack, move or anything

**Comment by Egzile** [comment]
This was done purposefull tyrantium.

**Comment by gp-Airee** [comment]
This is functioning as intended. All spawner mobs no longer have pathfinding or aggression logic.
