### ISSUE TITLE
Skyblock Server Down?

### ISSUE THREAD

**Issue by shreddybear** [theseedmc/issues#26]
**Describe the bug**
Can not connect to Skyblock from the lobby either by right clicking the NPC or typing /server skyblock.

**To Reproduce**
1. Connect to the lobby (I'm using 1.12.2)
2. Do /server skyblock or Right click the Skyblock NPC
![image](https://user-images.githubusercontent.com/51917702/59978628-643acf00-95ac-11e9-9506-5a18e30ea25f.png)

**Expected behavior**
Transfer to the Skyblock spawn

**Comment by Milkpaw** [comment]
This has been going on for about a week now, it's not something new. I'm also experiencing this.

**Comment by shreddybear** [comment]
Seems to be fixed now.
