### ISSUE TITLE
Vote was aknowledged, but no key was awarded

### ISSUE THREAD

**Issue by dangar202** [theseedmc/issues#27]
**Describe the bug**
All 6 (now only 5 are required) of my votes were registered by the server, but no key was awarded.

**To Reproduce**
1. Vote on all 5 servers.
2. Wait for server to recognize all of the votes.
3. You will be told in chat that your votes were recognized, and nothing will happen afterwards.

**Expected behavior**
Expected: Vote on all servers, you will be notified in chat, receive a key for voting.

**Comment by sush1panda** [comment]
im getting so mad with the voting 
i have been voting for the past days and still nothing and when i try to vote again it say i already voted but im still getting nothing and my friends r getting but y not me it so unfair for me and and im like about to quit that server coz it being unfair with the voting when everyone getting it and not me

**Comment by gp-Airee** [comment]
Should be fixed. .org was not sending votes to the right proxy.
