### ISSUE TITLE
Guardians are being stupid without a player nearby.

### ISSUE THREAD

**Issue by Midport** [theseedmc/issues#28]
**Describe the bug**
Guardians are not moving in flowing water until player is nearby.

**To Reproduce**
1. Go to /warp Neptune on melon
2. Stand away from the bridge for a few minutes
3. See Guardians piling up
4. Move towards the Guardians and they will begin to move again.

![2019-06-23_16 23 01](https://user-images.githubusercontent.com/52054977/59983383-a6c3d200-95d3-11e9-97f6-57ac40c1e9d5.png)
(Guardians are piled up.)

**Expected behavior**
The guardians should be moving normally no matter if a player is close to them or not.

**Comment by CircusCow** [comment]
Entity activation range. This is working as it should.
