### ISSUE TITLE
Item disappearences

### ISSUE THREAD

**Issue by demonicheed** [theseedmc/issues#30]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Drop an item in the nether portal, its gone. Walk out on the other side, with no sight of it whatsoever, walk back and forth through the overworld and the nether, the item that you accidentally dropped or mined (i.e a shulker box near the portal) will be deleted forever.

**To Reproduce**
1. Go to 'any nether portal'
2. Drop your item in said nether portal.
3. Fireworks

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by gp-Airee** [comment]
Problem is in Multiverse Netherportals.
