### ISSUE TITLE
Add a warning/confirmation to warp publishing

### ISSUE THREAD

**Issue by dangar202** [theseedmc/issues#31]
**Is your feature request related to a problem? Please describe.**
Whenever you make a warp public, it takes $8,000 from your account. There is absolutely nothing that tells you this or warns you about this when you do it.

**Describe the solution you'd like**
Add some kind of confirmation that you would like to spend this amount of money before publishing the warp.

**Describe alternatives you've considered**
Put a tooltip under the publishing button that has a warning message with the price.

**Additional context**
Me (FelledHawk) and (9REDDRAGO) have lost a collective $28k due to this, we had absolutely no idea until we looked at our balances. This is why I am making this suggestion.

**Comment by nkomarn** [comment]
I will implement a solution immediately.

**Comment by nkomarn** [comment]
I implemented a system that allows you to choose whether a warp is private/public on warp creation. Within that menu, there is now a warning that displays the cost to create a public warp.

![image](https://user-images.githubusercontent.com/22900187/61176242-61f7df00-a572-11e9-9845-702059a11e52.png)
