### ISSUE TITLE
Warps arent working

### ISSUE THREAD

**Issue by yudheer** [theseedmc/issues#32]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
When trying to type /warp into the console an error message reading "an internal error occured while attempting to tab-complete this command" if you type /warp spawn or any other warp the error message reads "an internal error occured while attempting to perform this command"

**To Reproduce**
1. Join any server
2. type /warp followed by a space
3. The error message will spam

**Comment by nkomarn** [comment]
This is an issue with the updated warps system and has been reverted.
