### ISSUE TITLE
Warp bug

### ISSUE THREAD

**Issue by wouter222** [theseedmc/issues#33]
![2019-06-26_11 19 39](https://user-images.githubusercontent.com/52034946/60168281-d3aafb80-9804-11e9-9022-043d9f844172.png)
Hey!

Whenever you want to type in a warp (in melon at least), it gives out error messages with each letter you type and won't let you access the warp itself. This needs fixing fast, since warps are a main thing on The Seed. There should be a screenshot included, but if not, try it out yourself on Melon.

Thanks for looking into this,
Wouter222

**Comment by nkomarn** [comment]
This is an issue with the updated warps system and has been reverted.
