### ISSUE TITLE
Weekly vote count not resetting

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#34]
**Describe the bug**
Weekly vote count not resetting

**To Reproduce**
1. /votegui
2. hover over vote totals

**Expected behavior**
Vote count would reset after one week

![image](https://user-images.githubusercontent.com/51970925/60191098-c2acbb00-9801-11e9-9dd7-9563eb7397e8.png)

**Comment by yungwilder** [comment]
Also maybe related, I did not receive the weekly key at 30 votes, or the new 35 votes, so I may just have a bugged vote db entry.

**Comment by Egzile** [comment]
it hasn't been a week yet so its working fine

**Comment by Egzile** [comment]
repost the error if its still broken Monday methinks

**Comment by yungwilder** [comment]
@Egzile this is votes from last week onto today, it would be impossible for me to even get more than 42 votes in a week (with 6 voting sites, now 5) and I am currently sitting at 51 as of this update, definitely an issue.

**Comment by yungwilder** [comment]
Update: as of today at 63 votes I was awarded a weekly key for voting 35 times.

**Comment by yungwilder** [comment]
Just an update, as of the beginning of this week my votes were reset. Will leave open for @gp-Airee to close if the changeset for the fix was just not linked.

**Comment by gp-Airee** [comment]
:+1:
