### ISSUE TITLE
Mcmmo repair level

### ISSUE THREAD

**Issue by Hadjax420** [theseedmc/issues#35]
**Describe the bug**
My Mcmmo does not allow me to gain XP for my repair skill while repairing.
Please provide additional information too, depending on what you have issues with:
I have repaired on multiple instances and have not gotten past level 2.
**To Reproduce**
1. Go to a Minecraft Vanilla anvil
2. Enable action with the anvil
3. Repair an item to full repair when enchanted
4. No Experience will be gained 

**Expected behavior**
When going to an anvil I expected to be able to repair my armor that was enchanted to then gain levels in the area of repair, but when doing so I do not visually or statistically have these levels and have repaired many times on multi-enchanted items to full repair, but only get to level two, I do not see a popup like I would normally on an instance with Mining or digging and do not see a bar, this limits my ability to get better abilities when playing and would like to have it fixed so continue my expansion of abilities.

**Comment by gp-Airee** [comment]
Use McMMO anvils.

**Comment by Hadjax420** [comment]
> Use McMMO anvils.

I do not have level 10, so how would one get levels before being able to use McMMO ( i am level 2 and not progressing)
