### ISSUE TITLE
Weekly Crate but No Vote Crate

### ISSUE THREAD

**Issue by Hadjax420** [theseedmc/issues#36]
**Describe the bug**
I finished voting on 4 out of the five sites listed for voting, then received my Weekly Voting Crate Key, but since the new minimum is 4 i already should have received the vote crate key but did not and still have not.
**To Reproduce**
1. type in the vote command
2. complete voting for all sites
3. go back to game
4. Shave a Weekly Crate key but no Vote Crate Key

**Expected behavior**
I expected to receive a Weekly Vote Crate Key and Vote crate Key but only received the Weekly Crate Key, while completing 6/6 of the voting sites.

**Comment by gp-Airee** [comment]
Actively working to resolve issues with voting websites.
