### ISSUE TITLE
Can't upgrade hopper limit on Skyblock.

### ISSUE THREAD

**Issue by shreddybear** [theseedmc/issues#4]
Can't upgrade hopper limit on Skyblock.

**To Reproduce**
1. Go to /is
2. Choose  Upgrade Center
3. Choose  Hopper Limit Upgrade
Says "You have to buy a rank to upgrade this"
4. I have rank to be able to purchase this upgrade.
![image](https://user-images.githubusercontent.com/51917702/59609744-f4c56b00-90e5-11e9-8aee-478b00726db3.png)

**Expected behavior**
Upgrade hopper limit

**Comment by gp-Airee** [comment]
@CircusCow VIP++++ (@shreddybear's rank) has the appropriate permission for 500 hoppers yet they are being limited at "about 96." This could either be a problem in the permission or with the tracking.

**Comment by CircusCow** [comment]
I've quite honestly been looking into this for awhile now and I'm very stumped.

**Comment by gp-Airee** [comment]
Resolved I think.
