### ISSUE TITLE
Ability to tag an item in chat

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#40]
**Is your feature request related to a problem? Please describe.**
The only way I know to show an item and its stats to chat would be to kill someone with it so it shows up in the death message.

**Describe the solution you'd like**
A command similar to /iteminfo that would post the results of the items stats to the chat 

**Additional context**
May want a timer to avoid people spamming named items

**Comment by Egzile** [comment]
I don't know if you need a timer, bc spam is bannable

**Comment by nkomarn** [comment]
Will be added soon as a donor perk (rank required not decided yet).
