### ISSUE TITLE
Water flow problem

### ISSUE THREAD

**Issue by Skwangles** [theseedmc/issues#41]
**Describe the bug**
Please provide additional information too, depending on what you have issues with:
 - when a bucket is placed flow is restricted by invisible walls.
Is not on chunk borders, i checked.
When you place down a bucket, the water either doesn't flow over a specific area, or doesn't even flow outside the source block(Even when I placed a source block next to it then remove it to update.)

**To Reproduce**
1. Go to -5334, 60, 4918
2. Do 'Place a water source block and try to get it to flow.
3. Click on '....'
4. See bug occurring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
The water should flow to the right, or outwards or connect with the next source block placed(Second image.)
![2019-06-29_20 32 46](https://user-images.githubusercontent.com/37290813/60381698-1a228380-9aad-11e9-8e0f-1113e47e346f.png)
![2019-06-29_20 33 42](https://user-images.githubusercontent.com/37290813/60381708-345c6180-9aad-11e9-9a0f-53bdba8e767b.png)

**Comment by gp-Airee** [comment]
I see you got water flow working at this location. Closing ticket.
