### ISSUE TITLE
TpSign

### ISSUE THREAD

**Issue by polo002** [theseedmc/issues#42]
Hey, could I make a suggestion to improve the player experience. The plugin link below allows player's to create teleport signs which could used in shops for different floors, etc https://dev.bukkit.org/projects/tpsign

I've used this plugin before and although released years ago, it's worth giving it a go
A similar idea was used on a server I use to play on. It was well used by the community

**Comment by gp-Airee** [comment]
Plugin isn't usable in this current version.
