### ISSUE TITLE
i think this might be a bug or idk if it is an intend issue but i used my vote key and it poofed the crate used it and i didnt receive any items or XP the chat said i used my key to open a crate and nothing else

### ISSUE THREAD

**Issue by JohnKPeta** [theseedmc/issues#44]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
2. Do '....'
3. Click on '....'
4. See bug occouring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by gp-Airee** [comment]
im not going to read an issue where you ignored the entire lovely format i poured my soul into copying from somewhere else and put the entire report in the title
