### ISSUE TITLE
Normal players Cant make sub claims. /sc requires perms that arent allowed 

### ISSUE THREAD

**Issue by guacyourflac** [theseedmc/issues#45]
**Describe the bug**
A clear and concise description of what the bug is. (I cannot make a Sub claim for my mall because i do not have the correct permissions)
Please provide additional information too, depending on what you have issues with: 

**To Reproduce**
1. Go to '.Mushroom.'
2. Do '../claim to recieve a shovel and then type /sc and you will not have the correct permissions when only have player perms..'
3. See bug occouring

**Expected behavior**
The game without op or staff permission will tell you that you cant make a subclaim because you do not have permissions

**Comment by gp-Airee** [comment]
Use /subdivideclaims.
