### ISSUE TITLE
[Bug] Mason Job: Smelting doesn't give money or job XP

### ISSUE THREAD

**Issue by adrenalinetooth** [theseedmc/issues#47]
**Describe the bug**
Smelting netherrack into nether bricks doesn't give job XP or money.

**To Reproduce**

1. Insert netherrack and fuel into furnace
2. let netherrack cook
3. collect nether bricks
4. No XP or money is gained from smelting netherrack.

**Expected behavior**
Smelting nether bricks should give job xp and money as listed in the job activities for mason.

**Comment by gp-Airee** [comment]
increasing scope: seems nothing for Mason's smelting rewards works.

**Comment by gp-Airee** [comment]
increasing scope: jobs is a garbage plugin
