### ISSUE TITLE
Bug with 'mason' job - unable to get money from smelting anymore

### ISSUE THREAD

**Issue by adrenalinetooth** [theseedmc/issues#48]
**Describe the bug**
 On Mushroom server, mason job - Smelting ANYTHING no longer gives job experience or money.

**To Reproduce**
1. Try to smelt cobble, etc
2. You will smelt the material but not receive job exp or money.

**Expected behavior**
 I would expect to get money and exp from smelting.

**Comment by nkomarn** [comment]
I've heard people complain about multiple jobs being broken - not sure if they actually are, but just throwing that out there.

**Comment by nkomarn** [comment]
Duplicate of #47
