### ISSUE TITLE
Banned on Store

### ISSUE THREAD

**Issue by TripBlindKids** [theseedmc/issues#49]
Hello. I was trying to buy Premium Keys earlier today and I saw that I was "banned" on the store? I just recently joined TheSeedMC and haven't bought anything, yet. I don't see why I would've been banned, so.. Thank you for reading and hopefully this results in my unban. Thanks!

**Comment by gp-Airee** [comment]
Usually this is a result of chargebacks on other Tebex stores. @CircusCow
