### ISSUE TITLE
Removed Mob Cap for Villagers ONLY

### ISSUE THREAD

**Issue by Ducky-Lucky** [theseedmc/issues#5]
I understand that mob cap is a thing and it makes sense but the mob cap for villagers seems to be very inconsistent and villagers are already not easy to find and it really annoys ppl when their villagers that they spent ages finding all despawn bc of the mob cap. Can’t you guys just remove the mob cap for villagers bc it’s not like there’s ever going to be enough villagers for the server to lag intensely.

**Comment by gp-Airee** [comment]
Could you elaborate on "mob cap?" Are you referring to mob stacking or are your mobs being deleted?

**Comment by gp-Airee** [comment]
No response from poster. Assuming resolved with theseedmc/seed-casual-plugins@6d64c7215100d854606876a27abafe8362c80ba5
