### ISSUE TITLE
Perk: Money Boost

### ISSUE THREAD

**Issue by RustyAsparagus** [theseedmc/issues#50]
Hi I bought the 500k money boost that makes 50 an hour.  It was supposed to be indefinite but at the time it was made until you log off.  Is there any way to get a refund on the purchase.

Thanks!

**Comment by gp-Airee** [comment]
@CircusCow

**Comment by nkomarn** [comment]
It is actually working as intended at the moment, but we are going to remake the system to work like you expected it to within the coming days.
