### ISSUE TITLE
Realms displaying incorrect welcome realm

### ISSUE THREAD

**Issue by JustKuono** [theseedmc/issues#51]
![Screenshot_551](https://user-images.githubusercontent.com/46217876/60706754-c6120780-9ecf-11e9-9187-c0bbfeb7a065.png)
While on Pumpkin today a new member joined and it said "Welcome so-and-so to the Melon Realm" while on Pumpkin.

![Screenshot_552](https://user-images.githubusercontent.com/46217876/60706758-c8746180-9ecf-11e9-8d9b-5a1965652034.png)

**Comment by gp-Airee** [comment]
Solved problem.
