### ISSUE TITLE
Warps are not allowed to be created or deleted?

### ISSUE THREAD

**Issue by JustKuono** [theseedmc/issues#54]
Inability to create or remove warps. Typing /warp delete <warpname> does nothing but give an error, I may just be an idiot and not know how to input commands correctly. Pumpkin server.
![Screenshot_558](https://user-images.githubusercontent.com/46217876/60745662-ffcf2680-9f40-11e9-8738-af95d24f8fdb.png)
![Screenshot_559](https://user-images.githubusercontent.com/46217876/60745667-01005380-9f41-11e9-9153-b31bfeed25b2.png)
![Screenshot_560](https://user-images.githubusercontent.com/46217876/60745691-0fe70600-9f41-11e9-81c5-578c8b5ecdc6.png)
![Screenshot_561](https://user-images.githubusercontent.com/46217876/60745922-0e6a0d80-9f42-11e9-865c-dac06a530db5.png)
![Screenshot_562](https://user-images.githubusercontent.com/46217876/60745924-0f9b3a80-9f42-11e9-801d-57d7ec29e787.png)

**Comment by yungwilder** [comment]
@JustKuono just use the command /warp

They added a UI that handles all the common commands

**Comment by JustKuono** [comment]
> @JustKuono just use the command /warp
> They added a UI that handles all the common commands

Thank you, I was unaware of this ;m;

**Comment by gp-Airee** [comment]
that help command is deprecated and has been removed, thanks for the report.
