### ISSUE TITLE
I died for no reason, I was doing nothing that couldve killed me. i was in the ocean getyting gravel, full health, full enchanted armor. died in a snap with full breath and hunger. no hostile mobs anywhere. and my stuff appeared back in my inv after death.

### ISSUE THREAD

**Issue by AfflictioonGPspot1cat** [theseedmc/issues#56]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
2. Do '....'
3. Click on '....'
4. See bug occouring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by gp-Airee** [comment]
I WILL NOT READ BUG REPORTS WITH A DEFAULT TEMPLATE AND THE ENTIRE REQUEST IN THE TITLE
