### ISSUE TITLE
/perks prem keys

### ISSUE THREAD

**Issue by androidies** [theseedmc/issues#57]
![Untitled](https://user-images.githubusercontent.com/52681444/60848288-e72f6c80-a1dd-11e9-9d91-3f2c0cf686a8.png)

Helllo,
Did today staff fixed /perks and i cant claim prem keys show "I claimed a key"
Please fix or something.
Thanks.

P.s Can i have one prem key? :> Server melon. (AndroiDies)

**Comment by nkomarn** [comment]
@androidies Have you clicked the claim key button within the past week? You only get a single key per week.
