### ISSUE TITLE
Ender Chest and Experience Levels Gone

### ISSUE THREAD

**Issue by SanjanaG25** [theseedmc/issues#58]
Ender Chests empty and all items missing. All experience levels are lost.

1. Go to the Melon Server
3. Click on ur ender chest/look at experience levels
4. See bug occouring

All experience levels are returned and items in ender chests come back

**Comment by gp-Airee** [comment]
This has been resolved. We accidently switched primary world files from the spawn world to the wilderness world, but playerdata was being stored in the spawn world. Oops.
