### ISSUE TITLE
Cant use ./skull and cant claim my weekly key

### ISSUE THREAD

**Issue by SomeHispanicGuy** [theseedmc/issues#59]
I cant use ./skull due it saying I already used it for the day but ive only used it once and that was around 4-5 days ago and for weekly key Im not certain but Im pretty sure its already been a week since ive claimed my last key and its not letting me claim my key for this week
![Screenshot](https://user-images.githubusercontent.com/52839624/61159022-a4fd7800-a4c8-11e9-930d-059b9d0faebf.png)

.

**Comment by nkomarn** [comment]
@SomeHispanicGuy This is an issue with the database code in SeedDonor. I will be taking measures to resolve this today.

**Comment by nkomarn** [comment]
Resolved in build 7 of SeedDonor.
