### ISSUE TITLE
No prize?

### ISSUE THREAD

**Issue by KurbStomples** [theseedmc/issues#60]
**Describe the bug**
I don't know if this is a one-off, but it might be as this is a first for me. I voted and took my vote key to the crate, and had the crate shove me back and tell me I wasn't allowed to utilize it. No prize, no nothing. :C

**To Reproduce**
1. Vote
2. Get Key
3. Take key to vote crate
4. ???
5. Don't profit

**Expected behavior**
I expected to get a prize! :CCCC
![No Key](https://user-images.githubusercontent.com/52848939/61168053-342c7f00-a50d-11e9-9655-b17b4b38118b.png)

**Comment by Fengsuave** [comment]
use /vote next
https://topminecraftservers.org/server/5340
http://bridgeurl.com/votelinks-1
https://minecraft-server.net/vote/TheSeedMC/
https://minecraft-server-list.com/server/437323/
https://www.planetminecraft.com/server/the-seed-1-13-survival-no-grief-pets-player-shops-friendly/
https://minecraft-mp.com/server/217122/vote/?error=1&time=

all links for vote !!

**Comment by KurbStomples** [comment]
I...know how to vite and how it works. The problem was I DID vote, got my key to get my reward, and was given no reward but lost the key. This is not user error lol this is server error.

**Comment by nkomarn** [comment]
![image](https://user-images.githubusercontent.com/22900187/61266807-565f1080-a74a-11e9-91da-675aca1ea943.png)
^ same issue from another player I saw on the Discord server

**Comment by gp-Airee** [comment]
Resolved with crate rework.
