### ISSUE TITLE
Missing Items On Death

### ISSUE THREAD

**Issue by Sairi123** [theseedmc/issues#61]
**Describe the bug**

I was looting a sunken ship, drowned before I could reach an air pocket created by a door in a 1x2 block space. I immediately used the /back command to return to the location and retrieve my items, spawned at the surface of the water, saw my items below and held shift to sink down and collect them. I opened my inventory and then saw I was missing half of it. Broke some nearby blocks to see if the items were stuck out of sight, and no luck. Swam around to see if they got flung somewhere, and nothing. 

Some items that are missing include:
- Black shulker box containing 2 full stacks of torches, 1 full stack of coal, 2 shears, and a few other items. Not sure if it contained any recent loot at time of death, though it is likely I had just moved my valuable loot into it.
- about half a stack or more of iron ingots
-  at least 13 emeralds
- at least 5 diamonds
- a heart of the sea
- Iron leggings and iron boots (both were worn at time of death)
It is likely this is not all the items I lost, it's just what I recall that is for sure missing.

**To Reproduce**
1. Go to Coordinates X -9403, Y 56, Z 41482 in the Mushroom Realm
2. Drown right above the door, with items in inventory
3. Use the /back chat command to return to location of death and retrieve inventory
4. See bug occurring. Check for missing items. *I have not tried to see if this is reproducible*

**Expected behavior**

I expected my full inventory to be there upon respawning with the /back command.

**Comment by Fengsuave** [comment]
The same happened to me, not hard anything in the water just disappeared very fast

**Comment by gp-Airee** [comment]
Issue maybe resolved.
