### ISSUE TITLE
Went to melon server, instantly died in the void

### ISSUE THREAD

**Issue by CaptainCarKeys** [theseedmc/issues#65]
I was on the Mushroom server in the end, and I did /spawn. Then I did /server melon and instantly started to take void damage for no reason, this bug has happened to another player before. 
![Capture](https://user-images.githubusercontent.com/52926070/61226763-0b64df00-a6f1-11e9-8078-0e8a0b146c82.jpg)

**Comment by CircusCow** [comment]
Please PM me on discord so we can discuss this.
