### ISSUE TITLE
Cannot create a warp on trusted land

### ISSUE THREAD

**Issue by KittieCraft** [theseedmc/issues#66]
**Describe the bug**
On land where you are trusted, but do not own yourself, you cannot create a warp. It says “Claimed Land! You can’t make warps in other’s land!”
**To Reproduce**
1. Go to someone else’s land where you are trusted
2. Try to create a warp
3. See bug occouring

**Expected behavior**
Given that you are trusted on said land, the expected behavior is to create a warp with no issues

**Comment by gp-Airee** [comment]
@nkomarn relates to your recent commit theseedmc/SeedWarp@359057094613575de173d66fb9bc4d70d507727c. please add checks for trust.

**Comment by nkomarn** [comment]
Resolved issue in build 10 of SeedWarp.
