### ISSUE TITLE
/craft or craft table

### ISSUE THREAD

**Issue by androidies** [theseedmc/issues#70]
Morning i joined server melon and say "Welcome to the Melon server" After 30min i cant make diamond armor or something from craft table. Please fix
![dwa](https://user-images.githubusercontent.com/52681444/61487665-653e0100-a99e-11e9-896d-8d6f0c88ae1d.png)
![fa](https://user-images.githubusercontent.com/52681444/61487667-653e0100-a99e-11e9-8eb8-f9e505563680.png)

**Comment by androidies** [comment]
I use /craft and no show Gold Block to Gold Ingot. I cant make Gold Block to Gold Ingot
![dwa2](https://user-images.githubusercontent.com/52681444/61487911-df6e8580-a99e-11e9-9fc5-d2952eff8c6c.png)

**Comment by CircusCow** [comment]
Interesting. Looking into this now

**Comment by CircusCow** [comment]
I cannot reproduce this issue. Can you try a different client version?

**Comment by androidies** [comment]
I use other version 1.13.2 Not work. :/ 
![gefea](https://user-images.githubusercontent.com/52681444/61496339-d0de9900-a9b3-11e9-8ec0-af574104ceed.png)

**Comment by CircusCow** [comment]
Is it with crafting tables and /craft?

**Comment by androidies** [comment]
I use /craft. Craft table same not work

**Comment by gp-Airee** [comment]
Solved
