### ISSUE TITLE
Absence of Phantoms

### ISSUE THREAD

**Issue by WhimsicalRain** [theseedmc/issues#71]
**Describe the bug**
I haven’t been asleep in at least 10+ Minecraft days and there have been no phantoms in sight.
This makes one of the donor perks for automatically killing phantoms with beams, useless.

**To Reproduce**
1. Don't go to sleep for 3+ Minecraft days
2. Ta-da, no phantoms in sight.

**Expected behavior**
Obviously, expected behavior would be the absence of phantoms. This is occurring in Pumpkin, but I'm not sure if Mushroom and Melon are also affected by this as well.

**Comment by nkomarn** [comment]
This is a known issue. We are currently trying to figure out the cause of this.

**Comment by ArcturasRann** [comment]
Most players hate phantoms anyway. If you put them back, make them fly lower and act stupid.
