### ISSUE TITLE
Allowing People to access entities on Someones Claim

### ISSUE THREAD

**Issue by Frozenblooo** [theseedmc/issues#72]
**Describe the solution you'd like**
I think that there should be a command like /entitytrust, so that people can use item frames, villagers and other entities on other peoples claim.

**Describe alternatives you've considered**
There is one option to this which is /trust, but people don't want other people to be able to break and place blocks in their shops etc. 

**Additional context**
If this feature is added it will allow people to make villager trading halls and shops that use redstone instead of chest shop.

**Comment by nkomarn** [comment]
@Frozenblooo You can give containertrust, but this would also allow people to use chests in the area. However, it does work.

**Comment by gp-Airee** [comment]
Not on the roadmap.
