### ISSUE TITLE
Playtime doesn't work properly

### ISSUE THREAD

**Issue by Quechuor** [theseedmc/issues#73]
**Describe the bug**
The playtime isn't displayed properly, I am settler but it shows only 1 hour of playtime.

**To Reproduce**

2. Do /playtime

**Expected behavior**
It should show that I have +12hours of playtime.
![2019-07-26_10 31 39](https://user-images.githubusercontent.com/53334319/61938594-c6af3280-af91-11e9-9e0b-ea819e5b132d.png)

**Comment by gp-Airee** [comment]
Merging issues with playtime with all. There seems to have been some data loss due to the database endpoint not being reset when moving database hosting providers.

**Comment by gp-Airee** [comment]
/playtime seems to be working again. We're gonna do a DB migration to MongoDB soon.
