### ISSUE TITLE
Playtime command fully doesn't work for me

### ISSUE THREAD

**Issue by Redstoner89** [theseedmc/issues#74]
I **don't** think I have to say much about this. When I type **/playtime** in _chat_, the **following** _**error**_ _message_ comes out: _"An internal error occurred while attempting to perform this command_"
I don't know if that is posted on discord, but I don't think so. I don't know if that happens to all players or just me.

What I did
1. **I joined the Melon realm**
2. **I wanted to see my playtime**
3. **I typed the command "_/playtime_"**
4. **That error message shows up**

![PROOOOOF](https://user-images.githubusercontent.com/53334870/61940265-52768e00-af95-11e9-881d-3609d1c62ae5.png)

[thisisavideobutitisn'tallowed.zip](https://github.com/theseedmc/issues/files/3435079/thisisavideobutitisn.tallowed.zip)

thatra's all doka byueeee

tysm for reading! <3

**Comment by Redstoner89** [comment]
h**e**l**p**

**Comment by gp-Airee** [comment]
Duplicate of #73

**Comment by Redstoner89** [comment]
No. It's not. I don't even think that you saw the image, but okay.
