### ISSUE TITLE
Villager trade interactions with Mypet

### ISSUE THREAD

**Issue by Zytan27** [theseedmc/issues#77]
**Describe the bug**
When making a villager a pet, it resets the villager's trade history. Usually a librarian should have around 8-12 total trades, and then it locks to prevent more trades from being acquired. When you store the librarian as a pet, it resets that counter, and opens the villager to have another 8 or so trades. This cycle repeats until the villager has around 150-200+ trades at which point the villager trade window breaks from overflow, and you can no longer trade with them. After the village has hit overflow point, minecraft stop displaying trades. There is literally just a blank screen when you open its trade window. This only works on 1.13, as in 1.14 client they updated the trading window. If you are in a 1.14 client when you attempt to trade with the overflow villager, it crashes your client and says unexpected packet size. 100% reproduction rate. I've done this with 4 villagers at this point. I mentioned this on Discord, but was just ignored. This is fairly irritating as it's ruined several good librarians and farmers for me now.

**To Reproduce**
1. Get a trading villager.
2. Trade with it until you reach the max trade count for that villager.
3. Store it as a pet, and release again.
4. Trade with it until you reach new max trade count.
5. Repeat ad naseum until you reach ~200 trades and the overflow of data breaks the client.

**Expected behavior**
Storing a villager as a pet shouldn't break trading.
![2019-07-31_18 48 25](https://user-images.githubusercontent.com/52572218/62253462-e98f7b80-b3c3-11e9-9a05-7d2a4a559699.png)

**Comment by gp-Airee** [comment]
Leashing villagers has been made impossible.
