### ISSUE TITLE
Creeper Heads In-Game

### ISSUE THREAD

**Issue by CHEEZUS908** [theseedmc/issues#79]
Creeper Heads In-Game so people are able to use them for banners. /Skull creeper gives you "Creeper's Head" which can be used for a decoration but won't work when making banner design. This is not a huge issue but more of a slight annoyance. I understand if it's not able to be fixed but I just thought I should bring it to light since it hinders banner creations.

**Comment by nkomarn** [comment]
@CHEEZUS908 Skulls of creepers, skeletons, and zombies can already be obtained in vanilla by blowing up said mob with a charged creeper. We are not looking to add them to /skull because we want to keep these items rare.
