### ISSUE TITLE
Remove shulkers from the mob stacker

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#8]
**Is your feature request related to a problem? Please describe.**
Shulkers do not respawn and are currently being lost to the stack clear, which does not seem like a great mechanic combination. 

**Describe the solution you'd like**
As suggested by KBXCN (and others) in discord, they should be either or exempt from stacking or immune to the clear. 

**Additional context**
I personally have not witnessed this but I know others have mentioned it before so it is not an isolated incident.

**Comment by gp-Airee** [comment]
We'll handle this when we migrate off WildStacker and to Java 11.

**Comment by gp-Airee** [comment]
Closing with 6d64c72.
