### ISSUE TITLE
Donator Jumpping Issue

### ISSUE THREAD

**Issue by AfflictioonGPspot1cat** [theseedmc/issues#80]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
2. Do '....'
3. Click on '....'
4. See bug occouring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by AfflictioonGPspot1cat** [comment]
When entering the Nether then leaving, Donators lose their ability to double jump and have to restart to get it back, thanks for your time!

**Comment by yungwilder** [comment]
unless you edit your post and actually follow the format Airee will remove this.

**Comment by nkomarn** [comment]
@AfflictioonGPspot1cat This is a known issue. Double jumping gets enabled immediately upon world change, but a delay needs to be added when coming to/from the nether. This will be resolved in the next update of SeedDonor.
