### ISSUE TITLE
Archduke and Only Able to Have One Particle Effect

### ISSUE THREAD

**Issue by CrabbyLynn** [theseedmc/issues#82]
I am only able to have one particle effect at a time, even after purchasing Archduke Rank. It says I have reached the maximum amount of particles that I can create. This happened after I upgraded from Baron to Archduke, but I am not sure if that is related to the problem. Thank you.
Image: (https://user-images.githubusercontent.com/47096530/62407727-49c42000-b572-11e9-99d2-6a0ba8d22665.png)

**Comment by CrabbyLynn** [comment]
Username is Lynnea_

**Comment by nkomarn** [comment]
@CrabbyLynn This is intentional. We initially allowed more than 1 effect, but recently changed the maximum for all ranks to 1 particle at a time.
