### ISSUE TITLE
Witches aren’t stacking

### ISSUE THREAD

**Issue by GoldenArgonaut** [theseedmc/issues#83]
Describing the bug:
Well, this is sort of a straightforward bug report. We were just told that Witches were one of the mobs that were supposed to be stacked, and currently they do not stack and witch grinders have loads of these mobs that have their AI still functioning.

Reproducing the bug (?)
Go to melon, do /warp mobxp, and the very backmost platform has witches. Unless it’s been fixed already, you’re probably going to get poisoned by 20 witches if you stand too close.

**Comment by nkomarn** [comment]
> Describing the bug:
> Well, this is sort of a straightforward bug report. We were just told that Witches were one of the mobs that were supposed to be stacked, and currently they do not stack and witch grinders have loads of these mobs that have their AI still functioning.
> 
> Reproducing the bug (?)
> Go to melon, do /warp mobxp, and the very backmost platform has witches. Unless it’s been fixed already, you’re probably going to get poisoned by 20 witches if you stand too close.

@GoldenArgonaut This is not an issue. Working as intended. We removed stacking from witches after the announcement.
