### ISSUE TITLE
Pigmen Spawners 

### ISSUE THREAD

**Issue by Snickerswhirr** [theseedmc/issues#85]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Pigmen spawners are spawning stacked pigmen but once they are hit their AI activates and they try to attack the player.
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
1. Go to pigmen spawner and wait for a pigmen to spawn.
2. Attack said pigmen once.
3. Pigmen should then try to aggro.
4. See bug occouring

**Expected behavior**
Spawned mobs from a spawner should not have AI. Expected them to stand there and do nothing, instead they aggro'd to player even when stacked.

**Comment by nkomarn** [comment]
@Snickerswhirr I just realized - everything is operating as it should. Spawner mobs all have nerfed AI, which means they have no pathfinding ability. This is why they don't aggro.

**Comment by gp-Airee** [comment]
@nkomarn Post says "Expected them to stand there and do nothing, instead they aggro'd to player even when stacked." Mason fixed Craftistacker to nerf spawner mobs though, so we should be good now.
