### ISSUE TITLE
Villager ai

### ISSUE THREAD

**Issue by ThisIsOlaf** [theseedmc/issues#86]
Villager ai isn't working. Villagers only move once in a few minutes, for the rest of the time they stand still. This is both the case with villagers I've petted and with villagers from villagers. Both don't seem to have an ai. 

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
2. Do '....'
3. Click on '....'
4. See bug occouring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by gp-Airee** [comment]
:clap: if :clap: you :clap: ignore :clap: the :clap: format :clap: im :clap: going :clap: to :clap: ignore :clap: you :clap:
