### ISSUE TITLE
There are 2 base claims from 2 separate people who have been offline for over 3 months, shouldn't the claims be gone by now?

### ISSUE THREAD

**Issue by Shady420** [theseedmc/issues#88]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

**To Reproduce**
2. Do '....'
3. Click on '....'
4. See bug occouring

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by nkomarn** [comment]
👏 follow 👏 the 👏 format
