### ISSUE TITLE
Claim systems

### ISSUE THREAD

**Issue by Shady420** [theseedmc/issues#89]
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
I have a claim and others have claims surrounding it, they have passed the time limit where the claim should be removed (3 months)

**To Reproduce**
1. Go to claim
2. Check their last seen time (one is 3 months and 11 days, the other is 3 months and 19 days)
3. The claim is still active

**Expected behavior**
The claim should have expired and been removed by now
![unknown](https://user-images.githubusercontent.com/54226348/63220088-7d3fa680-c13d-11e9-8d83-4565b2f26182.png)
![unknown (1)](https://user-images.githubusercontent.com/54226348/63220089-7d3fa680-c13d-11e9-85d4-d097991187d9.png)

**Comment by Shady420** [comment]
noticed one of them is only 1 month my bad I provided the wrong screen shot

**Comment by Shady420** [comment]
Here is the other guy 
![unknown (2)](https://user-images.githubusercontent.com/54226348/63220101-cee83100-c13d-11e9-8a07-544c782fb94d.png)

**Comment by gp-Airee** [comment]
There's no claim autoremoval.
