### ISSUE TITLE
Premium Kit possible fix

### ISSUE THREAD

**Issue by yudheer** [theseedmc/issues#9]
**Is your feature request related to a problem? Please describe.**
The current premium kit for archdukes has been broken for a while, I understand that the staff
is aware of the issue and currently working on it.

**Describe the solution you'd like**
I cannot speak for others but personally I never use the archduke kit anymore, the armor and tools provided is not that great and I have much better stuff available to me. 
Perhaps it would be easier to add the premium key to the archduke kit and change the archduke kit redeem timer from 24hours to a week.This can be a sort of temp fix while the premium kit is worked on. Perhaps run a poll asking archdukes if they use the kit or wouldn't mind the cool-down being extended to a week

**Comment by gp-Airee** [comment]
@nkomarn will be commissioned to work on a global kit cooldown for Essentials. Once this is finished, we can restore premium kit to all servers.

**Comment by gp-Airee** [comment]
Will be part of theseedmc/SeedDonor I believe.
