### ISSUE TITLE
Item Duplication Issue (possibly tied in with the Mob Stacking issue)

### ISSUE THREAD

**Issue by GeorgeHoctor** [theseedmc/issues#90]
So the Mob Stacking issue where mobs are losing their AI And are unable to be killed has already been reported but I think this is spreading to items as well. My Minecarts at the Townville entrance have duplicated and cannot be ridden and are just being in the way. The carts pictured are both the duplicated ones that cannot be ridden, broken, or moved. They won't even fall when the tracks are removed. 
![20190821132052_1](https://user-images.githubusercontent.com/52613560/63453626-15c47800-c417-11e9-93be-f9acba0ecc04.jpg)

**Comment by nkomarn** [comment]
This is a known issue and is being worked on.

**Comment by gp-Airee** [comment]
Resolved and pushed to production.
