### ISSUE TITLE
Mypet - Ride skilltree with horse variations

### ISSUE THREAD

**Issue by Zytan27** [theseedmc/issues#91]
**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Under the Mypet system, any pet that has the ride skilltree chosen at level 10 can fly. Winged pets have slowfall built in, but all pets are supposed to do so. The issue lies in when you attempt to fly with a Horse, or Skeleton Horse. These to begin with don't fly very well, they don't gain altitude much, and they also tend to randomly fall. The main problem is that the visual animation of the horse isn't synced with the actual position in the world. It will appear that you are flying or riding in one place, and then you'll either get randomly teleported, or when you dismount you end up falling somewhere unpleasant and die. 

**To Reproduce**
1. Tame a horse, and then make a pet.
2. Type /pcst and choose the ride skilltree
3. Level to 10
4. Attempt to fly on that horse, and notice the buggy flying.
5. Go flying for an extended distance, and then dismount. Watch as you aren't in the location you'd expect.

**Expected behavior**
Horse flying visuals shouldn't desync with the actual position in the world. 

This isn't quite a 100% reproduction, but happens the vast majority of the time. I've since just released my skeleton horse as it was useless due to the above reasons, so I don't have a video. Should be very easy to replicate however.

**Comment by nkomarn** [comment]
@Zytan27 This is an issue with https://github.com/xXKeyleXx/MyPet. Maybe open an issue over on their GitHub page.
