### ISSUE TITLE
Legends Bow Reflects Back

### ISSUE THREAD

**Issue by Kirache** [theseedmc/issues#95]
**Describe the bug**
Attacking stacked mobs with Legends Bow sometimes causes the arrow to bounce back. The mob is set on fire, but the arrow reflects back towards me. I can't tell if the mob always actually gets damaged apart from burning, it kind of seems like sometimes it doesn't. If it hits me it knocks me back but does not set me on fire or deal damage. I tried relogging and it still happens.

**To Reproduce**

I did it on Mushroom at warp FreeFood

1. Hit stacked mob with Legends Bow

**Comment by gp-Airee** [comment]
Fixed.
