### ISSUE TITLE
Nether Warp Instant Death Glitch

### ISSUE THREAD

**Issue by rockyourboxes** [theseedmc/issues#96]
**Describe the bug**
When using a warp to the nether after relocating it in the overworld, you will go to the coordinates in the Nether instead of the Overworld. This means that you could have warps inside of blocks, killing you instantly, which is what happened to me.

**To Reproduce**

1. Set a warp in the Nether.
2.Go to ANY place in the Overworld
3. Relocate the same Warp when in the overworld
4. Warp to the warp you relocated.
5. You will go to the coordinates you set the warp to in the Overworld, but you will be in the nether.

**Expected behavior**
Relocating warps in-between the Nether and the Overworld should change which dimension it is in respectively.

**Comment by nkomarn** [comment]
Resolved in https://github.com/theseedmc/SeedWarp/commit/db4b3a0790976f9183547c0b8f77759617eb611a.

**Comment by gp-Airee** [comment]
Pushed to production theseedmc/Seed-Casual-Plugins@83f0749982ef9f4b3c489ca1430c98d799f5d043.
