### ISSUE TITLE
Add Plugin "PlayerMention"

### ISSUE THREAD

**Issue by xKeny** [theseedmc/issues#97]
**Is your feature request related to a problem? Please describe.**
I am building a lot, and not watching chat. this will notify me when I am mentioned in chat 

**Describe the solution you'd like**
A noise occurs when I/other staff members are mentioned in chat

**Describe alternatives you've considered**
constantly watching chat

**Additional context**
plugin link https://www.spigotmc.org/resources/playermention-completely-recoded.8963/

**Comment by nkomarn** [comment]
Would be insanely easy to implement.
